/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_about_dialog (void)
{
  GtkWidget *about_dialog;
  const gchar *authors[] = {
    "Bert Timmerman <bert.timmerman@xs4all.nl>",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");
  GdkPixbuf *about_dialog_logo_pixbuf;

  about_dialog = gtk_about_dialog_new ();
  gtk_widget_set_name (about_dialog, "about_dialog");
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (about_dialog), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (about_dialog), _("pcb-gfpw"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (about_dialog), _("(C) 2007 Bert Timmerman."));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (about_dialog), _("pcb Footprint Wizard generates footprint files for pcb.\n"));
  gtk_about_dialog_set_license (GTK_ABOUT_DIALOG (about_dialog), _("GPL v2"));
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (about_dialog), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (about_dialog), translators);
  about_dialog_logo_pixbuf = create_pixbuf ("splash_wiz.xpm");
  gtk_about_dialog_set_logo (GTK_ABOUT_DIALOG (about_dialog), about_dialog_logo_pixbuf);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about_dialog, about_dialog, "about_dialog");

  return about_dialog;
}

GtkWidget*
create_pcb_gfpw (void)
{
  GtkWidget *pcb_gfpw;
  GdkPixbuf *pcb_gfpw_icon_pixbuf;
  GtkWidget *vbox3;
  GtkWidget *hbox2;
  GtkWidget *notebook;
  GtkWidget *table4;
  GtkWidget *frame15;
  GtkWidget *alignment15;
  GtkWidget *table18;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *footprint_author_entry;
  GtkWidget *footprint_dist_license_entry;
  GtkWidget *footprint_use_license_entry;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *footprint_status_entry;
  GtkWidget *label51;
  GtkWidget *frame16;
  GtkWidget *alignment16;
  GtkWidget *table19;
  GtkWidget *label7;
  GtkWidget *footprint_name_entry;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *footprint_type_entry;
  GtkWidget *footprint_type_entry;
  GtkWidget *package_is_radial_checkbutton;
  GtkWidget *label31;
  GtkWidget *label30;
  GtkWidget *label29;
  GtkWidget *package_body_height_entry;
  GtkWidget *package_body_width_entry;
  GtkWidget *package_body_length_entry;
  GtkWidget *label54;
  GtkWidget *footprint_value_entry;
  GtkWidget *label52;
  GtkWidget *label4;
  GtkWidget *table5;
  GtkWidget *frame11;
  GtkWidget *alignment11;
  GtkWidget *table14;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *pad_length_entry;
  GtkWidget *pad_width_entry;
  GtkWidget *label46;
  GtkWidget *frame6;
  GtkWidget *alignment6;
  GtkWidget *table11;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *pad_clearance_entry;
  GtkWidget *pad_solder_mask_clearance_entry;
  GtkWidget *label42;
  GtkWidget *frame10;
  GtkWidget *alignment10;
  GtkWidget *table13;
  GtkWidget *pad_diameter_entry;
  GtkWidget *label16;
  GtkWidget *pin_drill_diameter_entry;
  GtkWidget *label53;
  GtkWidget *label45;
  GtkWidget *frame9;
  GtkWidget *alignment9;
  GtkWidget *table12;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *number_total_pins_entry;
  GtkWidget *number_of_rows_entry;
  GtkWidget *number_of_columns_entry;
  GtkWidget *E2_entry;
  GtkWidget *E1_entry;
  GtkWidget *pad_shape_entry;
  GtkWidget *number_1_position_entry;
  GtkWidget *label44;
  GtkWidget *label5;
  GtkWidget *table6;
  GtkWidget *frame12;
  GtkWidget *alignment12;
  GtkWidget *table15;
  GtkWidget *thermal_checkbutton;
  GtkWidget *label24;
  GtkWidget *label34;
  GtkWidget *thermal_width_entry;
  GtkWidget *thermal_length_entry;
  GtkWidget *thermal_nopaste_checkbutton;
  GtkWidget *label47;
  GtkWidget *label6;
  GtkWidget *table8;
  GtkWidget *frame14;
  GtkWidget *alignment14;
  GtkWidget *table17;
  GtkWidget *courtyard_checkbutton;
  GtkWidget *label37;
  GtkWidget *label39;
  GtkWidget *horizontal_courtyard_entry;
  GtkWidget *vertical_courtyard_entry;
  GtkWidget *label50;
  GtkWidget *courtyard_line_width_entry;
  GtkWidget *label49;
  GtkWidget *frame13;
  GtkWidget *alignment13;
  GtkWidget *table16;
  GtkWidget *label38;
  GtkWidget *silkscreen_line_width_entry;
  GtkWidget *package_outline_checkbutton;
  GtkWidget *indicate_1_checkbutton;
  GtkWidget *label48;
  GtkWidget *label21;
  GtkWidget *frame3;
  GtkWidget *alignment3;
  GtkWidget *image1;
  GtkWidget *label3;
  GtkWidget *hbuttonbox2;
  GtkWidget *close_button;
  GtkWidget *clear_button;
  GtkWidget *save_button;
  GtkWidget *refresh_button;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  pcb_gfpw = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (pcb_gfpw, "pcb_gfpw");
  gtk_tooltips_set_tip (tooltips, pcb_gfpw, _("FootPrintWizard for pcb footprints"), NULL);
  gtk_window_set_title (GTK_WINDOW (pcb_gfpw), _("pcb FootPrintWizard"));
  pcb_gfpw_icon_pixbuf = create_pixbuf ("gFootprintWizard.xpm");
  if (pcb_gfpw_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (pcb_gfpw), pcb_gfpw_icon_pixbuf);
      gdk_pixbuf_unref (pcb_gfpw_icon_pixbuf);
    }

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (pcb_gfpw), vbox3);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox2, TRUE, TRUE, 0);

  notebook = gtk_notebook_new ();
  gtk_widget_set_name (notebook, "notebook");
  gtk_widget_show (notebook);
  gtk_box_pack_start (GTK_BOX (hbox2), notebook, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (notebook), 10);

  table4 = gtk_table_new (2, 1, FALSE);
  gtk_widget_set_name (table4, "table4");
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (notebook), table4);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook), table4,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 5);

  frame15 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame15, "frame15");
  gtk_widget_show (frame15);
  gtk_table_attach (GTK_TABLE (table4), frame15, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame15), GTK_SHADOW_OUT);

  alignment15 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment15, "alignment15");
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (frame15), alignment15);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment15), 0, 0, 12, 0);

  table18 = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (table18, "table18");
  gtk_widget_show (table18);
  gtk_container_add (GTK_CONTAINER (alignment15), table18);

  label25 = gtk_label_new (_("Author"));
  gtk_widget_set_name (label25, "label25");
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table18), label25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new (_("Distribution license "));
  gtk_widget_set_name (label26, "label26");
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table18), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  footprint_author_entry = gtk_entry_new ();
  gtk_widget_set_name (footprint_author_entry, "footprint_author_entry");
  gtk_widget_show (footprint_author_entry);
  gtk_table_attach (GTK_TABLE (table18), footprint_author_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, footprint_author_entry, _("Type your name here"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (footprint_author_entry), 8226);

  footprint_dist_license_entry = gtk_entry_new ();
  gtk_widget_set_name (footprint_dist_license_entry, "footprint_dist_license_entry");
  gtk_widget_show (footprint_dist_license_entry);
  gtk_table_attach (GTK_TABLE (table18), footprint_dist_license_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, footprint_dist_license_entry, _("License under which you distribute the file"), NULL);
  gtk_entry_set_text (GTK_ENTRY (footprint_dist_license_entry), _("GPL"));
  gtk_entry_set_invisible_char (GTK_ENTRY (footprint_dist_license_entry), 8226);

  footprint_use_license_entry = gtk_entry_new ();
  gtk_widget_set_name (footprint_use_license_entry, "footprint_use_license_entry");
  gtk_widget_show (footprint_use_license_entry);
  gtk_table_attach (GTK_TABLE (table18), footprint_use_license_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, footprint_use_license_entry, _("Allowable usage"), NULL);
  gtk_entry_set_text (GTK_ENTRY (footprint_use_license_entry), _("unlimited"));
  gtk_entry_set_invisible_char (GTK_ENTRY (footprint_use_license_entry), 8226);

  label27 = gtk_label_new (_("Use license"));
  gtk_widget_set_name (label27, "label27");
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table18), label27, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new (_("Status"));
  gtk_widget_set_name (label28, "label28");
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table18), label28, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  footprint_status_entry = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (footprint_status_entry, "footprint_status_entry");
  gtk_widget_show (footprint_status_entry);
  gtk_table_attach (GTK_TABLE (table18), footprint_status_entry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_status_entry), _("Experimental"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_status_entry), _("Private"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_status_entry), _("Public released"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_status_entry), _("Confirmed by peers"));

  label51 = gtk_label_new (_("<b>Author</b>"));
  gtk_widget_set_name (label51, "label51");
  gtk_widget_show (label51);
  gtk_frame_set_label_widget (GTK_FRAME (frame15), label51);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  frame16 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame16, "frame16");
  gtk_widget_show (frame16);
  gtk_table_attach (GTK_TABLE (table4), frame16, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame16), GTK_SHADOW_OUT);

  alignment16 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment16, "alignment16");
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (frame16), alignment16);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment16), 0, 0, 12, 0);

  table19 = gtk_table_new (8, 2, FALSE);
  gtk_widget_set_name (table19, "table19");
  gtk_widget_show (table19);
  gtk_container_add (GTK_CONTAINER (alignment16), table19);

  label7 = gtk_label_new (_("Name"));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table19), label7, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  footprint_name_entry = gtk_entry_new ();
  gtk_widget_set_name (footprint_name_entry, "footprint_name_entry");
  gtk_widget_show (footprint_name_entry);
  gtk_table_attach (GTK_TABLE (table19), footprint_name_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, footprint_name_entry, _("Type the name of the footprint here, no suffix please"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (footprint_name_entry), 8226);

  label8 = gtk_label_new (_("Type"));
  gtk_widget_set_name (label8, "label8");
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table19), label8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);

  label9 = gtk_label_new (_("Units"));
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table19), label9, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  footprint_type_entry = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (footprint_type_entry, "footprint_type_entry");
  gtk_widget_show (footprint_type_entry);
  gtk_table_attach (GTK_TABLE (table19), footprint_type_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("BGA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("CAPC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("CAPM"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("CAPMP"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("DIOM"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("INDC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("INDM"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("RESC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("RESM"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("TO92"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("TO220"));

  footprint_type_entry = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (footprint_type_entry, "footprint_type_entry");
  gtk_widget_show (footprint_type_entry);
  gtk_table_attach (GTK_TABLE (table19), footprint_type_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("mil"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("mil/100"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (footprint_type_entry), _("mm"));

  package_is_radial_checkbutton = gtk_check_button_new_with_mnemonic (_("Radial package "));
  gtk_widget_set_name (package_is_radial_checkbutton, "package_is_radial_checkbutton");
  gtk_widget_show (package_is_radial_checkbutton);
  gtk_table_attach (GTK_TABLE (table19), package_is_radial_checkbutton, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, package_is_radial_checkbutton, _("Check for a radial package"), NULL);

  label31 = gtk_label_new (_("Body height (H) "));
  gtk_widget_set_name (label31, "label31");
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table19), label31, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  label30 = gtk_label_new (_("Body width (Y)"));
  gtk_widget_set_name (label30, "label30");
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table19), label30, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  label29 = gtk_label_new (_("Body length (X)"));
  gtk_widget_set_name (label29, "label29");
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table19), label29, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  package_body_height_entry = gtk_entry_new ();
  gtk_widget_set_name (package_body_height_entry, "package_body_height_entry");
  gtk_widget_show (package_body_height_entry);
  gtk_table_attach (GTK_TABLE (table19), package_body_height_entry, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, package_body_height_entry, _("Type the height dimension of the package body here"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (package_body_height_entry), 8226);

  package_body_width_entry = gtk_entry_new ();
  gtk_widget_set_name (package_body_width_entry, "package_body_width_entry");
  gtk_widget_show (package_body_width_entry);
  gtk_table_attach (GTK_TABLE (table19), package_body_width_entry, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, package_body_width_entry, _("Type the width dimension of the package body here"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (package_body_width_entry), 8226);

  package_body_length_entry = gtk_entry_new ();
  gtk_widget_set_name (package_body_length_entry, "package_body_length_entry");
  gtk_widget_show (package_body_length_entry);
  gtk_table_attach (GTK_TABLE (table19), package_body_length_entry, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, package_body_length_entry, _("Type the length dimension of the package body here"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (package_body_length_entry), 8226);

  label54 = gtk_label_new (_("Value"));
  gtk_widget_set_name (label54, "label54");
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table19), label54, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label54), 0, 0.5);

  footprint_value_entry = gtk_entry_new ();
  gtk_widget_set_name (footprint_value_entry, "footprint_value_entry");
  gtk_widget_show (footprint_value_entry);
  gtk_table_attach (GTK_TABLE (table19), footprint_value_entry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, footprint_value_entry, _("Type the value of the package here"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (footprint_value_entry), 8226);

  label52 = gtk_label_new (_("<b>Footprint</b>"));
  gtk_widget_set_name (label52, "label52");
  gtk_widget_show (label52);
  gtk_frame_set_label_widget (GTK_FRAME (frame16), label52);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  label4 = gtk_label_new (_("Footprint"));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), label4);

  table5 = gtk_table_new (4, 1, FALSE);
  gtk_widget_set_name (table5, "table5");
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (notebook), table5);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook), table5,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_container_set_border_width (GTK_CONTAINER (table5), 5);

  frame11 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame11, "frame11");
  gtk_widget_show (frame11);
  gtk_table_attach (GTK_TABLE (table5), frame11, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame11), GTK_SHADOW_OUT);

  alignment11 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment11, "alignment11");
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (frame11), alignment11);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment11), 0, 0, 12, 0);

  table14 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table14, "table14");
  gtk_widget_show (table14);
  gtk_container_add (GTK_CONTAINER (alignment11), table14);

  label32 = gtk_label_new (_("Pad length (X) "));
  gtk_widget_set_name (label32, "label32");
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table14), label32, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  label33 = gtk_label_new (_("Pad width (Y)"));
  gtk_widget_set_name (label33, "label33");
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table14), label33, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);

  pad_length_entry = gtk_entry_new ();
  gtk_widget_set_name (pad_length_entry, "pad_length_entry");
  gtk_widget_show (pad_length_entry);
  gtk_table_attach (GTK_TABLE (table14), pad_length_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, pad_length_entry, _("Length of pads or diameter of pins"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (pad_length_entry), 8226);

  pad_width_entry = gtk_entry_new ();
  gtk_widget_set_name (pad_width_entry, "pad_width_entry");
  gtk_widget_show (pad_width_entry);
  gtk_table_attach (GTK_TABLE (table14), pad_width_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, pad_width_entry, _("Width of pads"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (pad_width_entry), 8226);

  label46 = gtk_label_new (_("<b>Pads</b>"));
  gtk_widget_set_name (label46, "label46");
  gtk_widget_show (label46);
  gtk_frame_set_label_widget (GTK_FRAME (frame11), label46);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame6, "frame6");
  gtk_widget_show (frame6);
  gtk_table_attach (GTK_TABLE (table5), frame6, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame6), GTK_SHADOW_OUT);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment6, "alignment6");
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (frame6), alignment6);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment6), 0, 0, 12, 0);

  table11 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table11, "table11");
  gtk_widget_show (table11);
  gtk_container_add (GTK_CONTAINER (alignment6), table11);

  label17 = gtk_label_new (_("Polygon clearance"));
  gtk_widget_set_name (label17, "label17");
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table11), label17, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new (_("Solder mask clearance "));
  gtk_widget_set_name (label18, "label18");
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table11), label18, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  pad_clearance_entry = gtk_entry_new ();
  gtk_widget_set_name (pad_clearance_entry, "pad_clearance_entry");
  gtk_widget_show (pad_clearance_entry);
  gtk_table_attach (GTK_TABLE (table11), pad_clearance_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, pad_clearance_entry, _("Clearance with polygons"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (pad_clearance_entry), 8226);

  pad_solder_mask_clearance_entry = gtk_entry_new ();
  gtk_widget_set_name (pad_solder_mask_clearance_entry, "pad_solder_mask_clearance_entry");
  gtk_widget_show (pad_solder_mask_clearance_entry);
  gtk_table_attach (GTK_TABLE (table11), pad_solder_mask_clearance_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, pad_solder_mask_clearance_entry, _("Clearance with solder mask"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (pad_solder_mask_clearance_entry), 8226);

  label42 = gtk_label_new (_("<b>Clearances</b>"));
  gtk_widget_set_name (label42, "label42");
  gtk_widget_show (label42);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label42);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  frame10 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame10, "frame10");
  gtk_widget_show (frame10);
  gtk_table_attach (GTK_TABLE (table5), frame10, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame10), GTK_SHADOW_OUT);

  alignment10 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment10, "alignment10");
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (frame10), alignment10);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment10), 0, 0, 12, 0);

  table13 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table13, "table13");
  gtk_widget_show (table13);
  gtk_container_add (GTK_CONTAINER (alignment10), table13);

  pad_diameter_entry = gtk_entry_new ();
  gtk_widget_set_name (pad_diameter_entry, "pad_diameter_entry");
  gtk_widget_show (pad_diameter_entry);
  gtk_table_attach (GTK_TABLE (table13), pad_diameter_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, pad_diameter_entry, _("Diameter of drill hole for pins"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (pad_diameter_entry), 8226);

  label16 = gtk_label_new (_("Pin drill diameter (d) "));
  gtk_widget_set_name (label16, "label16");
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table13), label16, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  pin_drill_diameter_entry = gtk_entry_new ();
  gtk_widget_set_name (pin_drill_diameter_entry, "pin_drill_diameter_entry");
  gtk_widget_show (pin_drill_diameter_entry);
  gtk_table_attach (GTK_TABLE (table13), pin_drill_diameter_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, pin_drill_diameter_entry, _("Diameter of drill hole for pins"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (pin_drill_diameter_entry), 8226);

  label53 = gtk_label_new (_("Pad diameter (D) "));
  gtk_widget_set_name (label53, "label53");
  gtk_widget_show (label53);
  gtk_table_attach (GTK_TABLE (table13), label53, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label53), 0, 0.5);

  label45 = gtk_label_new (_("<b>Pins</b>"));
  gtk_widget_set_name (label45, "label45");
  gtk_widget_show (label45);
  gtk_frame_set_label_widget (GTK_FRAME (frame10), label45);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  frame9 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame9, "frame9");
  gtk_widget_show (frame9);
  gtk_table_attach (GTK_TABLE (table5), frame9, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame9), GTK_SHADOW_OUT);

  alignment9 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment9, "alignment9");
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (frame9), alignment9);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment9), 0, 0, 12, 0);

  table12 = gtk_table_new (7, 2, FALSE);
  gtk_widget_set_name (table12, "table12");
  gtk_widget_show (table12);
  gtk_container_add (GTK_CONTAINER (alignment9), table12);

  label10 = gtk_label_new (_("Total pins and pads "));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table12), label10, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  label11 = gtk_label_new (_("Rows"));
  gtk_widget_set_name (label11, "label11");
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table12), label11, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  label12 = gtk_label_new (_("Columns"));
  gtk_widget_set_name (label12, "label12");
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table12), label12, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  label13 = gtk_label_new (_("Pitch (X)"));
  gtk_widget_set_name (label13, "label13");
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table12), label13, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  label14 = gtk_label_new (_("Pitch (Y)"));
  gtk_widget_set_name (label14, "label14");
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table12), label14, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label19 = gtk_label_new (_("Shape"));
  gtk_widget_set_name (label19, "label19");
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table12), label19, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label20 = gtk_label_new (_("Pin/pad #1 position "));
  gtk_widget_set_name (label20, "label20");
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table12), label20, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  number_total_pins_entry = gtk_entry_new ();
  gtk_widget_set_name (number_total_pins_entry, "number_total_pins_entry");
  gtk_widget_show (number_total_pins_entry);
  gtk_table_attach (GTK_TABLE (table12), number_total_pins_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, number_total_pins_entry, _("Total number of pins and pads"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (number_total_pins_entry), 8226);

  number_of_rows_entry = gtk_entry_new ();
  gtk_widget_set_name (number_of_rows_entry, "number_of_rows_entry");
  gtk_widget_show (number_of_rows_entry);
  gtk_table_attach (GTK_TABLE (table12), number_of_rows_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, number_of_rows_entry, _("Number of rows"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (number_of_rows_entry), 8226);

  number_of_columns_entry = gtk_entry_new ();
  gtk_widget_set_name (number_of_columns_entry, "number_of_columns_entry");
  gtk_widget_show (number_of_columns_entry);
  gtk_table_attach (GTK_TABLE (table12), number_of_columns_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, number_of_columns_entry, _("Number of columns"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (number_of_columns_entry), 8226);

  E2_entry = gtk_entry_new ();
  gtk_widget_set_name (E2_entry, "E2_entry");
  gtk_widget_show (E2_entry);
  gtk_table_attach (GTK_TABLE (table12), E2_entry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, E2_entry, _("Vertical pin/pad pitch"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (E2_entry), 8226);

  E1_entry = gtk_entry_new ();
  gtk_widget_set_name (E1_entry, "E1_entry");
  gtk_widget_show (E1_entry);
  gtk_table_attach (GTK_TABLE (table12), E1_entry, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, E1_entry, _("Horizontal pin/pad pitch"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (E1_entry), 8226);

  pad_shape_entry = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (pad_shape_entry, "pad_shape_entry");
  gtk_widget_show (pad_shape_entry);
  gtk_table_attach (GTK_TABLE (table12), pad_shape_entry, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  number_1_position_entry = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (number_1_position_entry, "number_1_position_entry");
  gtk_widget_show (number_1_position_entry);
  gtk_table_attach (GTK_TABLE (table12), number_1_position_entry, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label44 = gtk_label_new (_("<b>Common</b>"));
  gtk_widget_set_name (label44, "label44");
  gtk_widget_show (label44);
  gtk_frame_set_label_widget (GTK_FRAME (frame9), label44);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  label5 = gtk_label_new (_("Pins/Pads"));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), label5);

  table6 = gtk_table_new (1, 1, FALSE);
  gtk_widget_set_name (table6, "table6");
  gtk_widget_show (table6);
  gtk_container_add (GTK_CONTAINER (notebook), table6);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook), table6,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_container_set_border_width (GTK_CONTAINER (table6), 5);

  frame12 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame12, "frame12");
  gtk_widget_show (frame12);
  gtk_table_attach (GTK_TABLE (table6), frame12, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame12), GTK_SHADOW_OUT);

  alignment12 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment12, "alignment12");
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (frame12), alignment12);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment12), 0, 0, 12, 0);

  table15 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table15, "table15");
  gtk_widget_show (table15);
  gtk_container_add (GTK_CONTAINER (alignment12), table15);

  thermal_checkbutton = gtk_check_button_new_with_mnemonic (_("Thermal pad"));
  gtk_widget_set_name (thermal_checkbutton, "thermal_checkbutton");
  gtk_widget_show (thermal_checkbutton);
  gtk_table_attach (GTK_TABLE (table15), thermal_checkbutton, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, thermal_checkbutton, _("Check for a thermal pad"), NULL);

  label24 = gtk_label_new (_("Pad length (X)"));
  gtk_widget_set_name (label24, "label24");
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table15), label24, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label34 = gtk_label_new (_("Pad width (Y)"));
  gtk_widget_set_name (label34, "label34");
  gtk_widget_show (label34);
  gtk_table_attach (GTK_TABLE (table15), label34, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label34), 0, 0.5);

  thermal_width_entry = gtk_entry_new ();
  gtk_widget_set_name (thermal_width_entry, "thermal_width_entry");
  gtk_widget_show (thermal_width_entry);
  gtk_table_attach (GTK_TABLE (table15), thermal_width_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, thermal_width_entry, _("Width of thermal pad"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (thermal_width_entry), 8226);

  thermal_length_entry = gtk_entry_new ();
  gtk_widget_set_name (thermal_length_entry, "thermal_length_entry");
  gtk_widget_show (thermal_length_entry);
  gtk_table_attach (GTK_TABLE (table15), thermal_length_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, thermal_length_entry, _("Length of thermal pad"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (thermal_length_entry), 8226);

  thermal_nopaste_checkbutton = gtk_check_button_new_with_mnemonic (_("No paste on pad"));
  gtk_widget_set_name (thermal_nopaste_checkbutton, "thermal_nopaste_checkbutton");
  gtk_widget_show (thermal_nopaste_checkbutton);
  gtk_table_attach (GTK_TABLE (table15), thermal_nopaste_checkbutton, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, thermal_nopaste_checkbutton, _("Check for no paste on pad"), NULL);

  label47 = gtk_label_new (_("<b>Thermal pad</b>"));
  gtk_widget_set_name (label47, "label47");
  gtk_widget_show (label47);
  gtk_frame_set_label_widget (GTK_FRAME (frame12), label47);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  label6 = gtk_label_new (_("Thermal pad"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 2), label6);

  table8 = gtk_table_new (2, 1, FALSE);
  gtk_widget_set_name (table8, "table8");
  gtk_widget_show (table8);
  gtk_container_add (GTK_CONTAINER (notebook), table8);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook), table8,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_container_set_border_width (GTK_CONTAINER (table8), 5);

  frame14 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame14, "frame14");
  gtk_widget_show (frame14);
  gtk_table_attach (GTK_TABLE (table8), frame14, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame14), GTK_SHADOW_OUT);

  alignment14 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment14, "alignment14");
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (frame14), alignment14);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment14), 0, 0, 12, 0);

  table17 = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (table17, "table17");
  gtk_widget_show (table17);
  gtk_container_add (GTK_CONTAINER (alignment14), table17);

  courtyard_checkbutton = gtk_check_button_new_with_mnemonic (_("Print courtyard "));
  gtk_widget_set_name (courtyard_checkbutton, "courtyard_checkbutton");
  gtk_widget_show (courtyard_checkbutton);
  gtk_table_attach (GTK_TABLE (table17), courtyard_checkbutton, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, courtyard_checkbutton, _("Check to draw a courtyard (keepout)"), NULL);

  label37 = gtk_label_new (_("Width (Y)"));
  gtk_widget_set_name (label37, "label37");
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table17), label37, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  label39 = gtk_label_new (_("Length or diameter (X) "));
  gtk_widget_set_name (label39, "label39");
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table17), label39, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label39), 0, 0.5);

  horizontal_courtyard_entry = gtk_entry_new ();
  gtk_widget_set_name (horizontal_courtyard_entry, "horizontal_courtyard_entry");
  gtk_widget_show (horizontal_courtyard_entry);
  gtk_table_attach (GTK_TABLE (table17), horizontal_courtyard_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, horizontal_courtyard_entry, _("Length of courtyard"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (horizontal_courtyard_entry), 8226);

  vertical_courtyard_entry = gtk_entry_new ();
  gtk_widget_set_name (vertical_courtyard_entry, "vertical_courtyard_entry");
  gtk_widget_show (vertical_courtyard_entry);
  gtk_table_attach (GTK_TABLE (table17), vertical_courtyard_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, vertical_courtyard_entry, _("Width of courtyard"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (vertical_courtyard_entry), 8226);

  label50 = gtk_label_new (_("Line width"));
  gtk_widget_set_name (label50, "label50");
  gtk_widget_show (label50);
  gtk_table_attach (GTK_TABLE (table17), label50, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label50), 0, 0.5);

  courtyard_line_width_entry = gtk_entry_new ();
  gtk_widget_set_name (courtyard_line_width_entry, "courtyard_line_width_entry");
  gtk_widget_show (courtyard_line_width_entry);
  gtk_table_attach (GTK_TABLE (table17), courtyard_line_width_entry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, courtyard_line_width_entry, _("Line width for courtyard"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (courtyard_line_width_entry), 8226);

  label49 = gtk_label_new (_("<b>Courtyard</b>"));
  gtk_widget_set_name (label49, "label49");
  gtk_widget_show (label49);
  gtk_frame_set_label_widget (GTK_FRAME (frame14), label49);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  frame13 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame13, "frame13");
  gtk_widget_show (frame13);
  gtk_table_attach (GTK_TABLE (table8), frame13, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame13), GTK_SHADOW_OUT);

  alignment13 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment13, "alignment13");
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (frame13), alignment13);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment13), 0, 0, 12, 0);

  table16 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table16, "table16");
  gtk_widget_show (table16);
  gtk_container_add (GTK_CONTAINER (alignment13), table16);

  label38 = gtk_label_new (_("Line width"));
  gtk_widget_set_name (label38, "label38");
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table16), label38, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  silkscreen_line_width_entry = gtk_entry_new ();
  gtk_widget_set_name (silkscreen_line_width_entry, "silkscreen_line_width_entry");
  gtk_widget_show (silkscreen_line_width_entry);
  gtk_table_attach (GTK_TABLE (table16), silkscreen_line_width_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, silkscreen_line_width_entry, _("Line width for silkscreen"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (silkscreen_line_width_entry), 8226);

  package_outline_checkbutton = gtk_check_button_new_with_mnemonic (_("Print package outline "));
  gtk_widget_set_name (package_outline_checkbutton, "package_outline_checkbutton");
  gtk_widget_show (package_outline_checkbutton);
  gtk_table_attach (GTK_TABLE (table16), package_outline_checkbutton, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, package_outline_checkbutton, _("Check to draw package outline"), NULL);

  indicate_1_checkbutton = gtk_check_button_new_with_mnemonic (_("Pin/Pad #1 indicator "));
  gtk_widget_set_name (indicate_1_checkbutton, "indicate_1_checkbutton");
  gtk_widget_show (indicate_1_checkbutton);
  gtk_table_attach (GTK_TABLE (table16), indicate_1_checkbutton, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, indicate_1_checkbutton, _("Check to draw indicator for pin/pad #1"), NULL);

  label48 = gtk_label_new (_("<b>Silkscreen</b>"));
  gtk_widget_set_name (label48, "label48");
  gtk_widget_show (label48);
  gtk_frame_set_label_widget (GTK_FRAME (frame13), label48);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  label21 = gtk_label_new (_("Silkscreen"));
  gtk_widget_set_name (label21, "label21");
  gtk_widget_show (label21);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 3), label21);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame3, "frame3");
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (hbox2), frame3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 10);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_OUT);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (frame3), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 0, 0, 12, 0);

  image1 = create_pixmap (pcb_gfpw, "splash_wiz.xpm");
  gtk_widget_set_name (image1, "image1");
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (alignment3), image1);

  label3 = gtk_label_new (_("<b>Preview</b>"));
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label3);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox2), 10);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_SPREAD);

  close_button = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (close_button, "close_button");
  gtk_widget_show (close_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), close_button);
  GTK_WIDGET_SET_FLAGS (close_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, close_button, _("Click Close button to exit"), NULL);

  clear_button = gtk_button_new_from_stock ("gtk-clear");
  gtk_widget_set_name (clear_button, "clear_button");
  gtk_widget_show (clear_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), clear_button);
  GTK_WIDGET_SET_FLAGS (clear_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, clear_button, _("Click Save button to write footprint file"), NULL);

  save_button = gtk_button_new_from_stock ("gtk-save");
  gtk_widget_set_name (save_button, "save_button");
  gtk_widget_show (save_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), save_button);
  GTK_WIDGET_SET_FLAGS (save_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, save_button, _("Click Refresh button to update the Preview"), NULL);

  refresh_button = gtk_button_new_from_stock ("gtk-refresh");
  gtk_widget_set_name (refresh_button, "refresh_button");
  gtk_widget_show (refresh_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), refresh_button);
  GTK_WIDGET_SET_FLAGS (refresh_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) footprint_author_entry, "changed",
                    G_CALLBACK (on_footprint_author_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) footprint_dist_license_entry, "changed",
                    G_CALLBACK (on_footprint_dist_license_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) footprint_use_license_entry, "changed",
                    G_CALLBACK (on_footprint_use_license_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) footprint_status_entry, "changed",
                    G_CALLBACK (on_footprint_status_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) footprint_name_entry, "changed",
                    G_CALLBACK (on_footprint_name_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) footprint_type_entry, "changed",
                    G_CALLBACK (on_footprint_type_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) footprint_type_entry, "changed",
                    G_CALLBACK (on_footprint_type_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) package_is_radial_checkbutton, "toggled",
                    G_CALLBACK (on_package_is_radial_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) package_body_height_entry, "changed",
                    G_CALLBACK (on_package_body_height_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) package_body_width_entry, "changed",
                    G_CALLBACK (on_package_body_width_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) package_body_length_entry, "changed",
                    G_CALLBACK (on_package_body_length_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) pad_length_entry, "changed",
                    G_CALLBACK (on_pad_length_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) pad_width_entry, "changed",
                    G_CALLBACK (on_pad_width_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) pad_clearance_entry, "changed",
                    G_CALLBACK (on_pad_clearance_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) pad_solder_mask_clearance_entry, "changed",
                    G_CALLBACK (on_pad_solder_mask_clearance_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) pad_diameter_entry, "changed",
                    G_CALLBACK (on_pad_diameter_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) pin_drill_diameter_entry, "changed",
                    G_CALLBACK (on_pin_drill_diameter_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) number_total_pins_entry, "changed",
                    G_CALLBACK (on_number_total_pins_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) number_of_rows_entry, "changed",
                    G_CALLBACK (on_number_of_rows_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) number_of_columns_entry, "changed",
                    G_CALLBACK (on_number_of_columns_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) E2_entry, "changed",
                    G_CALLBACK (on_E2_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) E1_entry, "changed",
                    G_CALLBACK (on_E1_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) pad_shape_entry, "changed",
                    G_CALLBACK (on_pad_shape_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) number_1_position_entry, "changed",
                    G_CALLBACK (on_number_1_position_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) thermal_checkbutton, "toggled",
                    G_CALLBACK (on_thermal_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) thermal_width_entry, "changed",
                    G_CALLBACK (on_thermal_width_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) thermal_length_entry, "changed",
                    G_CALLBACK (on_thermal_length_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) thermal_nopaste_checkbutton, "toggled",
                    G_CALLBACK (on_thermal_nopaste_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) courtyard_checkbutton, "toggled",
                    G_CALLBACK (on_courtyard_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) horizontal_courtyard_entry, "changed",
                    G_CALLBACK (on_horizontal_courtyard_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) vertical_courtyard_entry, "changed",
                    G_CALLBACK (on_vertical_courtyard_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) courtyard_line_width_entry, "changed",
                    G_CALLBACK (on_courtyard_line_width_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) silkscreen_line_width_entry, "changed",
                    G_CALLBACK (on_silkscreen_line_width_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) package_outline_checkbutton, "toggled",
                    G_CALLBACK (on_package_outline_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) indicate_1_checkbutton, "toggled",
                    G_CALLBACK (on_indicate_1_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) close_button, "clicked",
                    G_CALLBACK (on_close_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear_button, "clicked",
                    G_CALLBACK (on_clear_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) save_button, "clicked",
                    G_CALLBACK (on_save_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh_button, "clicked",
                    G_CALLBACK (on_refresh_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (pcb_gfpw, pcb_gfpw, "pcb_gfpw");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table4, "table4");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, frame15, "frame15");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table18, "table18");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label25, "label25");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label26, "label26");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, footprint_author_entry, "footprint_author_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, footprint_dist_license_entry, "footprint_dist_license_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, footprint_use_license_entry, "footprint_use_license_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label27, "label27");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label28, "label28");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, footprint_status_entry, "footprint_status_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label51, "label51");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, frame16, "frame16");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table19, "table19");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label7, "label7");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, footprint_name_entry, "footprint_name_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label8, "label8");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label9, "label9");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, footprint_type_entry, "footprint_type_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, footprint_type_entry, "footprint_type_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, package_is_radial_checkbutton, "package_is_radial_checkbutton");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label31, "label31");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label30, "label30");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label29, "label29");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, package_body_height_entry, "package_body_height_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, package_body_width_entry, "package_body_width_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, package_body_length_entry, "package_body_length_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label54, "label54");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, footprint_value_entry, "footprint_value_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label52, "label52");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label4, "label4");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table5, "table5");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, frame11, "frame11");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table14, "table14");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label32, "label32");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label33, "label33");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, pad_length_entry, "pad_length_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, pad_width_entry, "pad_width_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label46, "label46");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table11, "table11");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label17, "label17");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label18, "label18");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, pad_clearance_entry, "pad_clearance_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, pad_solder_mask_clearance_entry, "pad_solder_mask_clearance_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label42, "label42");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, frame10, "frame10");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table13, "table13");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, pad_diameter_entry, "pad_diameter_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label16, "label16");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, pin_drill_diameter_entry, "pin_drill_diameter_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label53, "label53");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label45, "label45");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, frame9, "frame9");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table12, "table12");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label10, "label10");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label11, "label11");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label12, "label12");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label13, "label13");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label14, "label14");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label19, "label19");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label20, "label20");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, number_total_pins_entry, "number_total_pins_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, number_of_rows_entry, "number_of_rows_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, number_of_columns_entry, "number_of_columns_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, E2_entry, "E2_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, E1_entry, "E1_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, pad_shape_entry, "pad_shape_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, number_1_position_entry, "number_1_position_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label44, "label44");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label5, "label5");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table6, "table6");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, frame12, "frame12");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table15, "table15");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, thermal_checkbutton, "thermal_checkbutton");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label24, "label24");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label34, "label34");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, thermal_width_entry, "thermal_width_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, thermal_length_entry, "thermal_length_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, thermal_nopaste_checkbutton, "thermal_nopaste_checkbutton");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label47, "label47");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label6, "label6");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table8, "table8");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, frame14, "frame14");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table17, "table17");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, courtyard_checkbutton, "courtyard_checkbutton");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label37, "label37");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label39, "label39");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, horizontal_courtyard_entry, "horizontal_courtyard_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, vertical_courtyard_entry, "vertical_courtyard_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label50, "label50");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, courtyard_line_width_entry, "courtyard_line_width_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label49, "label49");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, frame13, "frame13");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, table16, "table16");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label38, "label38");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, silkscreen_line_width_entry, "silkscreen_line_width_entry");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, package_outline_checkbutton, "package_outline_checkbutton");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, indicate_1_checkbutton, "indicate_1_checkbutton");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label48, "label48");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label21, "label21");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, image1, "image1");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, label3, "label3");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, close_button, "close_button");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, clear_button, "clear_button");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, save_button, "save_button");
  GLADE_HOOKUP_OBJECT (pcb_gfpw, refresh_button, "refresh_button");
  GLADE_HOOKUP_OBJECT_NO_REF (pcb_gfpw, tooltips, "tooltips");

  return pcb_gfpw;
}

