/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifndef __INTERFACE_H_INCLUDED__
#define __INTERFACE_H_INCLUDED__


GtkWidget* create_pcb_gfpw (void);
GtkWidget* create_filechooser_dialog (void);


#endif /* __INTERFACE_H_INCLUDED__ */


/* EOF */
