/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

G_BEGIN_DECLS /* keep c++ happy */

GtkWidget* create_about_dialog (void);
GtkWidget* create_pcb_gfpw (void);
GtkWidget* create_filechooser_dialog (void);

G_END_DECLS /* keep c++ happy */
